var puckt=puckt||{};
puckt.util=function(){var c=function(a){return a/puckt.pxpm},b=function(a,b){return a>b?a-b:b-a},b=function(a,b){return a>b?a-b:b-a};return{pixelsToMetres:c,metresToPixels:function(a){return a*puckt.pxpm},degreesToRadians:function(a){return a*(Math.PI/180)},radiansToDegrees:function(a){return a*(180/Math.PI)},clamp:function(a,b,e){return Math.min(Math.max(e,a),b)},findDiff:b,dimTob2Vec2:function(a){return new box2d.b2Vec2(c(a.x),c(a.y))},calcVelocity:function(a,d){var e=c(a[a.length-1]-a[0]),f=b(d[0],
d[d.length-1]);return e/(0.0010*f)},setCanvasSize:function(a,b,e){a.setAttribute("width",b);a.setAttribute("height",e)},extendObject:function(a,b){for(var e in b)a[e]=b[e]},resetWorld:function(a){for(var b=a.GetBodyList();null!==b;)a.DestroyBody(b),b=b.GetNext();stage.removeAllChildren()}}}();"use strict";puckt=puckt||{};
puckt.flick=function(){var c=[],b=function(a){var b=function(){var b=[],d={},g=function(c){a.body.SetLinearVelocity(new box2d.b2Vec2(0,0));a.setPosition(puckt.util.clamp(a.radius+1,puckt.canvas.width-a.radius-1,c.stageX+d.x),puckt.util.clamp(puckt.canvas.height-104+a.radius,puckt.canvas.height-a.radius-1,c.stageY+d.y));b.push({pos:{x:c.rawX,y:c.rawY},timestamp:c.nativeEvent.timeStamp})},h=function(d){var h,g;if(2<b.length&&(20<b.length?b.splice(0,0.9*b.length):10<b.length&&b.splice(0,0.7*b.length),
d=b.length-1,h=puckt.util.calcVelocity([b[0].pos.x,b[d].pos.x],[b[0].timestamp,b[d].timestamp]),g=puckt.util.calcVelocity([b[0].pos.y,b[d].pos.y],[b[0].timestamp,b[d].timestamp]),h=new box2d.b2Vec2(h*puckt.Puck.realMass,g*puckt.Puck.realMass),b[d].pos.y>=puckt.canvas.height-112+puckt.Puck.realRadius)){a.body.ApplyImpulse(h,a.body.GetWorldCenter());d=c.slice();for(var f in d)d[f]()}};return function(b){var c=a.body.GetPosition();300<puckt.util.metresToPixels(c.y)&&(a.body.SetLinearVelocity(new box2d.b2Vec2(0,
0)),d={x:puckt.util.metresToPixels(c.x)-b.stageX,y:puckt.util.metresToPixels(c.y)-b.stageY},b.addEventListener("mousemove",g),b.addEventListener("mouseup",h))}}();a.shape.addEventListener("mousedown",b)};return{init:function(a){a.body.GetMass();b(a)},attachEvents:b,addFlickEventListener:function(a){c.push(a)},removeAllFlickEventListeners:function(){c.length=0}}}();"use strict";puckt=puckt||{};
puckt.Obj=function(){return Class.extend({init:function(c,b,a){this.fixDef=new box2d.b2FixtureDef;this.bodyDef=new box2d.b2BodyDef;this.shape=new createjs.Shape;this.shape.x=a.x;this.shape.y=a.y;this.shape.regX=a.w/2;this.shape.regY=a.h/2;this.shape.rotation=a.rotation||0;this.shape.type=b;this.w=a.w;this.h=a.h;puckt.util.extendObject(this.fixDef,a.fixDef);puckt.util.extendObject(this.bodyDef,a.bodyDef);this.bodyDef.position=puckt.util.dimTob2Vec2(a);this.bodyDef.bullet=!0;this.bodyDef.angle=puckt.util.degreesToRadians(this.shape.rotation);
this.body=this.shape.body=c.CreateBody(this.bodyDef);this.body.CreateFixture(this.fixDef);this.body.SetUserData(this.shape)},setPosition:function(c,b){this.body.SetPosition(puckt.util.dimTob2Vec2({x:c,y:b,w:this.w,h:this.h}))}})}();"use strict";puckt=puckt||{};
puckt.Puck=function(){function c(){var a=this.body.GetPosition();this.shape.set({x:puckt.util.metresToPixels(a.x),y:puckt.util.metresToPixels(a.y),rotation:puckt.util.radiansToDegrees(this.body.GetAngle())})}var b=puckt.Obj.extend({init:function(a,d){var e;e=new box2d.b2CircleShape(puckt.util.pixelsToMetres(d.radius));this._super(a,"puck",{x:d.x,y:d.y,w:2*d.radius,h:2*d.radius,fixDef:{density:b.realMass/(Math.PI*Math.pow(b.realRadius,2)),friction:1,restitution:0.8,shape:e},bodyDef:{type:box2d.b2Body.b2_dynamicBody,
angle:d.angle||puckt.util.degreesToRadians(0)}});this.radius=d.radius;this.body.SetLinearDamping(0.4);this.shape.graphics.beginFill("#222222").drawCircle(d.radius,d.radius,d.radius);this.shape.addEventListener("tick",c.bind(this))},isInFlickZone:function(){return!0}});b.realMass=17;b.realRadius=3.81;b.image=null;return b}();"use strict";puckt=puckt||{};
puckt.Wall=function(){var c=puckt.Obj.extend({init:function(b,a){var d;d=new box2d.b2PolygonShape;d.SetAsBox(puckt.util.pixelsToMetres(a.w)/2,puckt.util.pixelsToMetres(a.h)/2);this.lightColour=void 0===a.lightColour?"#92d548":a.lightColour;this.on=!0===a.lightOn&&this.isLightWall();this._super(b,"wall",{x:a.x,y:a.y,w:a.w,h:a.h,rotation:a.angle,fixDef:{density:5,friction:1,restitution:0.8,shape:d},bodyDef:{type:box2d.b2Body.b2_staticBody,angle:puckt.util.degreesToRadians(a.angle||0)}});this.shape.collision=
this.collision.bind(this);this.shape.isOn=this.isOn.bind(this);this.setLightSwitch(!0===a.isOn);this.collisionEvents=[function(){this.toggleLight()}.bind(this)]},isLightWall:function(){return null!==this.lightColour},isOn:function(){return this.on},toggleLight:function(){this.setLightSwitch(!this.on)},setLightSwitch:function(b){if(this.isLightWall()&&!c.disabled){var a;a=(this.on=b)?this.lightColour:c.offColour;this.shape.graphics.clear();this.shape.graphics.beginFill(a).drawRect(0,0,this.w,this.h);
this.shape.shadow=b?new createjs.Shadow(a,0,0,15):null}},collision:function(b){for(var a in this.collisionEvents)this.collisionEvents[a].call(this,b);c.collisionHandler.call(this,b)},addEventListener:function(b,a){"collision"==b&&this.collisionEvents.push(a)}});c.disabled=!1;c.collisionHandler=function(){};c.offColour="#222222";return c}();"use strict";puckt=puckt||{};
puckt.Level=function(){function c(b,a){this.world=b;this.number=a;this.collisions=this.lightWallsOn=this.initialLightsOn=this.lightWalls=0;this.last=!1}c.prototype.boot=function(b,a){var d=this,c=new XMLHttpRequest;c.open("GET","levels/"+this.number+".json",!0);c.responseType="text";c.onload=function(f){200==this.status?(d.data=JSON.parse(c.responseText),b(f)):a(f)};c.send(null)};c.prototype.begin=function(){var b=this;this.reset();this.last=b.data.last;puckt.Wall.collisionHandler=function(){b.finished||
(b.collisions++,this.isLightWall()&&(this.isOn()?b.lightWallsOn++:b.lightWallsOn--),b.lightWalls===b.lightWallsOn&&b._levelComplete())};this._drawBoundaries(this.data.boundaries);this._drawWalls(this.data.walls);this._drawPuck(this.data.puck);this.lightWallsOn=this.initialLightsOn;1===this.number&&!localStorage.getItem("seenTutorial")&&puckt.ui.tutorial()};c.prototype.reset=function(){this.lightWallsOn=this.initialLightsOn=this.lightWalls=0;this.finished=!0;this.collisions=0;this.last=!1;puckt.util.resetWorld(this.world);
this.finished=!1;puckt.Wall.disabled=!1};c.successCallback=function(){};c.failCallback=function(){};c.prototype._levelComplete=function(){this.finished=puckt.Wall.disabled=!0;var b=0,a;for(a in this.data.stars)if(this.collisions<=this.data.stars[a])b++;else break;0<b?c.successCallback.call(this,b,this.collisions):c.failCallback.call(this,b,this.collisions)};c.prototype._failLevel=function(){c.failCallback.call(this,this.collisions)};c.prototype._drawBoundaries=function(b){b=b||{};switch(!0){case !1!==
b.top:new puckt.Wall(this.world,{lightColour:null,x:puckt.canvas.width/2,y:0,w:puckt.canvas.width,h:0});case !1!==b.right:new puckt.Wall(this.world,{lightColour:null,x:puckt.canvas.width,y:puckt.canvas.height/2,w:0,h:puckt.canvas.height});case !1!==b.bottom:new puckt.Wall(this.world,{lightColour:null,x:puckt.canvas.width/2,y:puckt.canvas.height,w:puckt.canvas.width,h:0});case !1!==b.left:new puckt.Wall(this.world,{lightColour:null,x:0,y:puckt.canvas.height/2,w:0,h:puckt.canvas.height})}};c.prototype._drawWalls=
function(b){if(b.length)for(var a=0,d=b.length;a<d;a++){var c=new puckt.Wall(this.world,{x:b[a].coords.x,y:b[a].coords.y,w:b[a].dimensions.w,h:b[a].dimensions.h,angle:b[a].angle,lightColour:b[a].lightColour,lightOn:b[a].lightOn});c.isLightWall()&&(this.lightWalls++,c.isOn()&&this.initialLightsOn++);stage.addChild(c.shape)}};c.prototype._drawPuck=function(b){b=new puckt.Puck(this.world,{x:b.coords.x,y:b.coords.y,radius:b.radius});stage.addChild(b.shape);puckt.flick.init(b)};return c}();"use strict";
puckt=puckt||{};
puckt.Game=function(){function c(){document.getElementById("ice-rink").classList.remove("hidden");a=new box2d.b2World(new box2d.b2Vec2(0,0),!0);var b=new Box2D.Dynamics.b2ContactListener;b.BeginContact=function(a){var b=a.GetFixtureA().GetBody().GetUserData();(b.type="wall")&&b.collision(a)};a.SetContactListener(b);puckt.debug.init(a);e=new puckt.Level(a,d);e.boot(function(){e.begin()},function(){puckt.ui.openPopup({content:"<p>We failed to open your level, please refresh or reload the game.</p>"})});puckt.ui.drawNavigation(e)}
function b(b){b.paused||(stage.update(),puckt.debug.run(a.DrawDebugData.bind(a)),a.Step(1/f,10,10),a.ClearForces())}var a,d,e,f=60;return function(g){stage=new createjs.Stage(puckt.canvas.elem);createjs.Touch.enable(stage);d=g;puckt.Level.successCallback=function(b,c){var d=this,f,g={number:d.number,stars:b,collisions:c};f={content:"<p>Congratulations, you completed level "+d.number+" with "+b+" star"+(1!=b?"s":"")+"!</p>",buttons:[{text:"Proceed",callback:function(){puckt.ui.closePopup();e.data.last?
puckt.ui.openPopup({content:"<h1>You're good!</h1><p>Nice job completing all the levels. You have officially been Puckt. Return soon for new levels and features.</p>",buttons:[{text:"Quit",callback:function(){location.reload()}}]}):(e=new puckt.Level(a,++d.number),e.boot(function(){e.begin()},function(){puckt.ui.openPopup({content:"<p>We failed to open your level, please refresh or reload the game.</p>",buttons:[{text:"Reload",callback:function(){location.reload()}}]})}),puckt.ui.drawNavigation(e))}}]};
b!=d.data.stars.length&&f.buttons.push({text:"Retry",callback:function(){puckt.ui.closePopup();e.begin()}});f.buttons.push({text:"Quit",callback:function(){location.reload()}});puckt.ui.openPopup(f);f=JSON.parse(localStorage.getItem("levelsCompleted"));f.push(g);localStorage.setItem("levelsCompleted",JSON.stringify(f))};puckt.Level.failCallback=function(b,a){puckt.ui.openPopup({content:"<p>Unlucky, you didn't "+(null===b?"turn on all the lights":"get any stars")+". Please try again.</p>",buttons:[{text:"Retry",
callback:function(){puckt.ui.closePopup();e.begin()}},{text:"Quit",callback:function(){location.reload()}}]})};c();createjs.Ticker.addEventListener("tick",b);createjs.Ticker.setFPS(f);createjs.Ticker.useRAF=!0}}();"use strict";puckt=puckt||{};
puckt.music=function(){function c(a,d){plau(a,d);b[a].removeEventListener("canplay",c)}var b={};return{load:function(a,c,e,f){b[a]=document.createElement("audio");b[a].setAttribute("src",c);b[a].addEventListener("canplay",e,!1);b[a].addEventListener("error",f,!1);b[a].load();puckt.debug.run(function(){b[a].volume=0});return b[a]},play:function(a,d){b[a]&&(d=d||0,4==b[a].readyState?(b[a].currentTime=d,b[a].play()):b[a].addEventListener("canplay",function(){c(a,d)}));return b[a]},stop:stop,setVolume:function(a,
c){b[a].volume=c},BACKGROUND_MUSIC:"bgMusic"}}();"use strict";puckt=puckt||{};puckt.debug=function(){return{init:function(c){},isOn:function(){return!1},run:function(c){},canvas:void 0}}();"use strict";puckt=puckt||{};
puckt.ui=function(){function c(a){var c=document.createElement("aside"),f=document.createElement("section"),g;c.className="message";f.innerHTML=a.content;c.style.width=puckt.canvas.width+"px";c.style.height=puckt.canvas.height+puckt.canvas.navHeight+"px";c.style.opacity="0";if(a.buttons)for(var h=0;h<a.buttons.length;h++)g=document.createElement("a"),g.href="",g.className="button",g.innerHTML=a.buttons[h].text,b(g,a.buttons[h]),f.appendChild(g);c.appendChild(f);document.body.appendChild(c);setTimeout(function(){c.style.opacity=
"1"},1)}function b(a,b){a.addEventListener("click",function(a){a.preventDefault();b.callback()})}function a(){var a=document.querySelectorAll(".message");a[0].style.opacity="0";setTimeout(function(){a[0]&&a[0].parentNode.removeChild(a[0])},250)}return{openPopup:c,closePopup:a,tutorial:function(){console.log("here");c({content:"<h1>Tutorial</h1><p>Welcome to Puckt.<p>",buttons:[{text:"Next",callback:function(){a();c({content:"Flick the puck to toggle the walls. Line up and release your shot below the blue line. Made a mistake? Don't fret mutton, use the reset button. The less collisions, the more stars. Happy days.</p>",
buttons:[{text:"Close",callback:function(){puckt.ui.closePopup()}}]})}}]});localStorage.setItem("seenTutorial",!0)},drawNavigation:function(a){var b=document.querySelector("nav"),c=document.createElement("nav"),g=document.createElement("a"),h=document.createElement("a"),k=document.createElement("span");b&&b.parentNode.removeChild(b);c.style.width=puckt.canvas.width+"px";c.style.height=puckt.canvas.navHeight+"px";k.id="level_text";k.innerHTML="Level "+a.number;g.className="left";g.href="";g.innerHTML=
'<i class="icon-large icon-arrow-left"></i>';g.style.height=puckt.canvas.navHeight+"px";g.style.width=puckt.canvas.navHeight+"px";g.addEventListener("click",function(){location.reload()});h.className="right";h.href="";h.innerHTML='<i class="icon-large icon-refresh"></i>';h.style.height=puckt.canvas.navHeight+"px";h.style.width=puckt.canvas.navHeight+"px";h.addEventListener("click",function(b){b.preventDefault();a.begin()},!1);c.appendChild(g);c.appendChild(h);c.appendChild(k);document.body.appendChild(c)}}}();
"use strict";var box2d,stage,puckt=puckt||{};puckt.canvas={elem:document.createElement("canvas"),width:320,height:410,navHeight:50};puckt.pxpm=30/puckt.Puck.realRadius;
puckt.main=function(){var c=function(a){document.body.appendChild(puckt.canvas.elem);puckt.canvas.elem.setAttribute("id","canvas");puckt.util.setCanvasSize(puckt.canvas.elem,puckt.canvas.width,puckt.canvas.height);new puckt.Game(a)},b=function(){puckt.music.load(puckt.music.BACKGROUND_MUSIC,"audio/background.mp3",function(a){puckt.music.play(puckt.music.BACKGROUND_MUSIC)},function(a){console.log("music fail",a)})};box2d={b2Vec2:Box2D.Common.Math.b2Vec2,b2BodyDef:Box2D.Dynamics.b2BodyDef,b2Body:Box2D.Dynamics.b2Body,
b2FixtureDef:Box2D.Dynamics.b2FixtureDef,b2Fixture:Box2D.Dynamics.b2Fixture,b2World:Box2D.Dynamics.b2World,b2MassData:Box2D.Collision.Shapes.b2MassData,b2PolygonShape:Box2D.Collision.Shapes.b2PolygonShape,b2CircleShape:Box2D.Collision.Shapes.b2CircleShape,b2DebugDraw:Box2D.Dynamics.b2DebugDraw};return{init:function(){var a={content:"<h1>Puckt</h1> <small>beta</small><p>Puckt is a mobile HTML5 game designed to test your visual and mathematical skills.</p>",buttons:[{text:"New Game",callback:function(){puckt.ui.closePopup();
localStorage.setItem("levelsCompleted",JSON.stringify([]));c(1)}}]};JSON.parse(localStorage.getItem("levelsCompleted"))&&0<JSON.parse(localStorage.getItem("levelsCompleted")).length&&a.buttons.push({text:"Continue Game",callback:function(){puckt.ui.closePopup();var a=JSON.parse(localStorage.getItem("levelsCompleted")).pop().number+1;c(a)}});puckt.debug.isOn()||navigator.userAgent.match(/iPhone/i)||navigator.userAgent.match(/iPod/i)?puckt.debug.isOn()||window.navigator.standalone?(b(),puckt.ui.openPopup(a)):
puckt.ui.openPopup({content:"<h1>Puckt</h1> <small>beta</small><p>To play, you must first add this page to your <strong>Home Screen</strong>.</p>"}):puckt.ui.openPopup({content:"<h1>Puckt</h1> <small>beta</small><p>This game requires an iPhone or iPod Touch running iOS 5 or above.</p>"})}}}();window.addEventListener("load",puckt.main.init,!1);
